- name: Install batch of packages
  become: true
  become_user: "sudonopw"
  command: >
    yay -S
      --answerclean none --answeredit none --answerupgrade none --answerdiff none
      --removemake --noconfirm --combinedupgrade --needed
      {% for pkg in packages %}
        {{ pkg | quote }}
      {% endfor %}